### ISSUE TITLE
duplicate close_pending positions causing random crash 

### ISSUE THREAD

**Issue by joshith** [joshith/OldMonk#16]
duplicate close_pending positions causing crash randomly

**Comment by joshith** [comment]
root caused- 
`
        #TODO: FIXME: redo order state machine generically, this is all a patchwork
        if current_order == None and order_status != "done":
            # see if this is a late/mixed up state msg for an already done order. What we do here, may not be correct
            if (order_side == 'buy'):
                current_order = self.get_traded_buy_order(order_id)
            else:
                current_order = self.get_traded_sell_order(order_id)
            
            if current_order:
                log.critical ("******** (%s) order done already, but (%s) state msg recvd, ignore for now, FIXME: FIXME:"%(order_side, order_status))
                return current_order    
`
Causing multiple entries of same order to be added in open_orders/sl_list/tp_list. 

`
15107 Let's count the messages!
15108 Unexpected error: (<type 'exceptions.Exception'>, Exception('Duplicate close pending position',), <traceback object at 0x7f54737b0      b00>) exception: Duplicate close pending position
15109 
15110 -- Goodbye! --
15111 Traceback (most recent call last):
15112   File "./OldMonk.py", line 291, in <module>
15113     oldmonk_main ()
15114   File "./OldMonk.py", line 110, in oldmonk_main
15115     process_market (market)
15116   File "./OldMonk.py", line 125, in process_market
15117     market.update_market_states()
15118   File "/home/jork/OldMonk/market/market.py", line 1038, in update_market_states
15119     self._handle_take_profit ()
15120   File "/home/jork/OldMonk/market/market.py", line 366, in _handle_take_profit
15121     trade_pos_l = self.order_book.get_take_profit_positions(self.get_market_rate())
15122   File "/home/jork/OldMonk/market/order_book.py", line 361, in get_take_profit_positions
15123     raise Exception("Duplicate close pending position")
15124 Exception: Duplicate close pending position
`
