### ISSUE TITLE
crash while trying to close position

### ISSUE THREAD

**Issue by joshith** [joshith/OldMonk#7]
Let's count the messages!
Unexpected error: (<type 'exceptions.Exception'>, Exception('Invalid open position for closing',), <traceback object at 0x7f5ee6be1d88>) exception: Invalid open position for closing

-- Goodbye! --
Traceback (most recent call last):
  File "./OldMonk.py", line 315, in <module>
    oldmonk_main ()
  File "./OldMonk.py", line 90, in oldmonk_main
    process_market (market)
  File "./OldMonk.py", line 108, in process_market
    market.consume_trade_signal (signal)
  File "/home/jork/OldMonk/market/market.py", line 1008, in consume_trade_signal
    trade_req_list += self._generate_trade_request( signal)
  File "/home/jork/OldMonk/market/market.py", line 602, in _generate_trade_request
    raise Exception("Invalid open position for closing")            
Exception: Invalid open position for closing

**Comment by joshith** [comment]
fix being worked on

**Comment by joshith** [comment]
fixed
